server:
  port: 9901

spring:
  application:
    name: cloud-consumer-service

eureka:
  client:
    #表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: true
    #是否从 EurekaServer 抓取已有的注册信息，默认为 true。单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7002/eureka/
