server:
  port: 7001

spring:
  application:
    name: master-eureka

eureka:
  instance:
    hostname: master #eureka服务端的实例名称
  client:
    #表示是否将自己注册进 EurekaServer 默认为 true。
    register-with-eureka: true
    #是否从 EurekaServer 抓取已有的注册信息，默认为 true。
    # 单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡
    fetchRegistry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7002/eureka/